Repository SRM-IST-KTR/githubsrm, pull requests merged in 2021-07, with the labels that each got.

#15 Dev
  .travis.yml
  ecosystem.config.js
  test.backend.config
  test.backend.sh
  test.config
  test.frontend.config
  test.frontend.sh
  test_runner.sh
Labels: Travis CI

#19 🚨 dependabot
  client/.gitignore
  client/yarn.lock
Labels: bug

#20 🔍 improve lighthouse audits
  client/components/index/benefits.tsx
  client/components/index/hero.tsx
  client/components/join-us/maintainer/maintainer.tsx
  client/components/shared/footer.tsx
  client/pages/404.tsx
  client/pages/500.tsx
  client/pages/_document.tsx
  client/pages/contact-us.tsx
  client/pages/join-us/contributor.tsx
  client/pages/join-us/index.tsx
  client/pages/join-us/maintainer/existing-project.tsx
  client/pages/join-us/maintainer/index.tsx
  client/pages/join-us/maintainer/new-project.tsx
  client/pages/projects.tsx
  client/pages/team.tsx
Labels: enhancement

#25 Paginated projects
  server/githubsrm/administrator/test.py
  server/githubsrm/administrator/views.py
Labels: enhancement

#26 Fix bugs
  server/githubsrm/administrator/utils.py
Labels: enhancement

#30 Resolve Single project get route
  server/githubsrm/administrator/utils.py
  server/githubsrm/administrator/views.py
  server/githubsrm/apis/__init__.py
  server/githubsrm/apis/checks_models.py
  server/githubsrm/apis/models.py
Labels: enhancement

#37 Dev at auth
  server/githubsrm/administrator/definitions.py
  server/githubsrm/administrator/issue_jwt.py
  server/githubsrm/administrator/middleware.py
  server/githubsrm/administrator/models.py
  server/githubsrm/administrator/perms.py
  server/githubsrm/administrator/utils.py
  server/githubsrm/administrator/views.py
  server/githubsrm/apis/__init__.py
  server/githubsrm/apis/checks_models.py
  server/githubsrm/apis/models.py
  server/githubsrm/apis/open_views.py
  server/githubsrm/apis/utils.py
Labels: bug, enhancement

#44 FAQ Page
  client/components/faq/faq.tsx
  client/components/shared/layout.tsx
  client/components/shared/navbar.tsx
  client/pages/faq.tsx
  client/utils/FAQ data/faqdata.ts
  client/utils/FAQ data/minus.tsx
  client/utils/FAQ data/plus.tsx
  client/utils/titles/faq.tsx
  client/utils/titles/index.tsx
Labels: enhancement

#45 🚑 model error
  server/githubsrm/maintainer/models.py
Labels: bug

#51 ✨ maintainer auth
  server/githubsrm/maintainer/definitions.py
  server/githubsrm/maintainer/models.py
  server/githubsrm/maintainer/urls.py
  server/githubsrm/maintainer/views.py
Labels: enhancement

#54 Added basic email logic
  server/githubsrm/administrator/views.py
  server/githubsrm/apis/utils.py
Labels: enhancement

#55 ✨ JWT checks
  server/githubsrm/maintainer/definitions.py
  server/githubsrm/maintainer/utils.py
Labels: enhancement

#56 🚧 Email fixes
  server/githubsrm/administrator/views.py
  server/githubsrm/apis/utils.py
Labels: enhancement

#59 Refactored email function
  server/githubsrm/apis/utils.py
Labels: enhancement

#71 Email templates added
  server/githubsrm/apis/templates/1.html
  server/githubsrm/apis/templates/10.html
  server/githubsrm/apis/templates/11.html
  server/githubsrm/apis/templates/2.html
  server/githubsrm/apis/templates/3.html
  server/githubsrm/apis/templates/4.html
  server/githubsrm/apis/templates/5.html
  server/githubsrm/apis/templates/6.html
  server/githubsrm/apis/templates/7.html
  server/githubsrm/apis/templates/8.html
  server/githubsrm/apis/templates/9.html
  server/githubsrm/apis/templates/alpha_maintainer_code.html
  server/githubsrm/apis/templates/beta_maintainer_accept.html
  server/githubsrm/apis/utils.py
Labels: enhancement

#86 ➖ Remove react-icons
  client-portals/components/admin/dashboard/accepted-projects/accepted-projects-cards.tsx
  client-portals/components/admin/dashboard/index.tsx
  client-portals/components/maintainer/dashboard/dashboard.tsx
  client-portals/package.json
  client-portals/pages/admin/dashboard/[slug].tsx
  client-portals/pages/admin/dashboard/accepted-projects/[slug].tsx
  client-portals/pages/maintainer/dashboard/[slug].tsx
  client-portals/utils/icons/card-github.tsx
  client-portals/utils/icons/cross.tsx
  client-portals/utils/icons/next.tsx
  client-portals/utils/icons/previous.tsx
  client-portals/utils/icons/tick.tsx
Labels: enhancement

#91 🐛 minor API call bugs
  client/client-landing/services/api.tsx
Labels: bug

#115 Version 3.0.0
  Procfile
  client/client-portals/components/admin/dashboard/accepted-projects/index.tsx
  client/client-portals/components/admin/dashboard/index.tsx
  client/client-portals/components/admin/dashboard/project-visibility-popup.tsx
  client/client-portals/components/admin/login.tsx
  client/client-portals/components/admin/register.tsx
  client/client-portals/components/maintainer/dashboard/dashboard.tsx
  client/client-portals/components/maintainer/dashboard/other-maintainers.tsx
  client/client-portals/components/maintainer/dashboard/reset-password.tsx
  client/client-portals/components/maintainer/login.tsx
  client/client-portals/components/shared/button.tsx
  client/client-portals/components/shared/card.tsx
  client/client-portals/components/shared/index.tsx
  client/client-portals/components/shared/layout.tsx
  client/client-portals/components/shared/navbar.tsx
  client/client-portals/components/shared/pagination-buttons.tsx
  client/client-portals/context/authContext.tsx
  client/client-portals/pages/_app.tsx
  client/client-portals/pages/admin/dashboard/[slug].tsx
  client/client-portals/pages/admin/dashboard/accepted-projects/[slug].tsx
  client/client-portals/pages/admin/index.tsx
  client/client-portals/pages/index.tsx
  client/client-portals/pages/maintainer/dashboard/[slug].tsx
  client/client-portals/services/api.tsx
  client/client-portals/styles/tailwind.styles.css
  client/client-portals/utils/functions/toast.tsx
  client/client-portals/utils/icons/card-github.tsx
  client/client-portals/utils/icons/cross.tsx
  client/client-portals/utils/icons/next.tsx
  client/client-portals/utils/icons/previous.tsx
  client/client-portals/utils/icons/tick.tsx
  client/client-portals/utils/interfaces.ts
  server/githubsrm/administrator/definitions.py
  server/githubsrm/administrator/issue_jwt.py
  server/githubsrm/administrator/middleware.py
  server/githubsrm/administrator/models.py
  server/githubsrm/administrator/urls.py
  server/githubsrm/administrator/utils.py
  server/githubsrm/administrator/views.py
  server/githubsrm/apis/definitions.py
  server/githubsrm/apis/open_views.py
  server/githubsrm/apis/utils.py
  server/githubsrm/core/settings.py
  server/githubsrm/core/urls.py
  server/githubsrm/maintainer/__init__.py
  server/githubsrm/maintainer/definitions.py
  server/githubsrm/maintainer/models.py
  server/githubsrm/maintainer/urls.py
  server/githubsrm/maintainer/utils.py
  server/githubsrm/maintainer/views.py
  server/poetry.lock
  server/pyproject.toml
  server/run_backend_tests.sh
  server/tests/__init__.py
  server/tests/test_admin.py
  server/tests/test_apis.py
  server/tests/test_full_flow.py
  server/tests/test_maintainer.py
Labels: releases

#121 💄 🍻 css fixes dont end :(
  client/client-portals/pages/_app.tsx
  client/client-portals/styles/tailwind.styles.css
  client/client-portals/utils/functions/toast.tsx
Labels: UI, bug

#122 💄 add navbar role
  client/client-portals/components/shared/navbar.tsx
Labels: enhancement

#123 🚑 critical hotfix : logout bugs
  client/client-portals/components/maintainer/dashboard/dashboard.tsx
  client/client-portals/services/api.tsx
Labels: bug

#128 💄 Minor UI Fixes
  client/client-portals/components/admin/dashboard/accepted-projects/index.tsx
  client/client-portals/components/admin/dashboard/index.tsx
  client/client-portals/components/maintainer/dashboard/dashboard.tsx
  client/client-portals/components/maintainer/dashboard/other-maintainers.tsx
  client/client-portals/components/shared/navbar.tsx
  client/client-portals/pages/admin/dashboard/[slug].tsx
  client/client-portals/pages/maintainer/dashboard/[slug].tsx
Labels: UI

#129 💄 Loader Fixes
  client/client-portals/pages/admin/dashboard/accepted-projects/[slug].tsx
Labels: UI
