Repository SRM-IST-KTR/githubsrm, pull requests merged in 2021-06, with the labels that each got.

#6 CI Integration Tests
  .travis.yml
  run_tests.sh
  test-config.txt
  test-runner
  test-runner.sh
Labels: Travis CI

#7 Fix Static Site Rendering
  .gitignore
  server/.gitignore
  server/githubsrm/apis/open_views.py
  server/githubsrm/core/settings.py
  server/githubsrm/core/urls.py
  server/poetry.lock
  server/pyproject.toml
  server/requirements.txt
Labels: bug, enhancement

#10 Conditional route handling
  server/githubsrm/apis/open_views.py
  server/githubsrm/apis/utils.py
  server/githubsrm/core/urls.py
Labels: bug

#11 🚸 member designation
  client/components/team/member.tsx
  client/services/api.tsx
  client/utils/interfaces.ts
Labels: enhancement
